/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventIndexRouteImport } from './routes/event/index'
import { Route as HostHostIdRouteImport } from './routes/host/$hostId'
import { Route as EventEventIdRouteImport } from './routes/event/$eventId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostHostIdRoute = HostHostIdRouteImport.update({
  id: '/host/$hostId',
  path: '/host/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/host/$hostId': typeof HostHostIdRoute
  '/event': typeof EventIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/host/$hostId': typeof HostHostIdRoute
  '/event': typeof EventIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/host/$hostId': typeof HostHostIdRoute
  '/event/': typeof EventIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/event/$eventId'
    | '/host/$hostId'
    | '/event'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/event/$eventId'
    | '/host/$hostId'
    | '/event'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/event/$eventId'
    | '/host/$hostId'
    | '/event/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  EventEventIdRoute: typeof EventEventIdRoute
  HostHostIdRoute: typeof HostHostIdRoute
  EventIndexRoute: typeof EventIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/': {
      id: '/event/'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$hostId': {
      id: '/host/$hostId'
      path: '/host/$hostId'
      fullPath: '/host/$hostId'
      preLoaderRoute: typeof HostHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  EventEventIdRoute: EventEventIdRoute,
  HostHostIdRoute: HostHostIdRoute,
  EventIndexRoute: EventIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
